site_name: Database Manager

nav:
  - API:
    - Description: API_Subpages/description.md
    - Query Builders: API_Subpages/query_builders.md
    - Execute Query: API_Subpages/execute_query.md
  - Readme: index.md
  - Maintainer Reference:
    - connection_manager.py: Maintainer_Subpages/connections.md
    - execute_query.py: Maintainer_Subpages/execute_query.md
    - query_builders.py: Maintainer_Subpages/query_builders.md

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: indigo
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime

plugins:
  - search
  - mkdocstrings

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
