[tool.ruff]

extend-select = ["C4", "SIM", "TCH", "N", "D", "UP", "FBT", "T10", "PT", "ARG", "PD"]
ignore = ["D407", "D406"]

line-length = 120

show-fixes = true

# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
]